# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, HUnit, text }:

cabal.mkDerivation (self: {
  pname = "cmark";
  version = "0.5.1";
  sha256 = "e13a2889a74d6c9dd27bbd506b89f4ee8841c98aac36dd22f30a68863efa5446";
  buildDepends = [ text ];
  testDepends = [ HUnit text ];
  meta = {
    homepage = "https://github.com/jgm/commonmark-hs";
    description = "Fast, accurate CommonMark (Markdown) parser and renderer";
    license = self.stdenv.lib.licenses.bsd3;
  };
})

