# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, Diff, filepath, mtl, parsec, regexPcre
, utf8String
}:

cabal.mkDerivation (self: {
  pname = "highlighting-kate";
  version = "0.6.1";
  sha256 = "cb57caf861bda046043575772ffc7fd4cd21dd63a0ecdf26b624c7e930e0f30e";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    blazeHtml filepath mtl parsec regexPcre utf8String
  ];
  testDepends = [ blazeHtml Diff filepath ];
  prePatch = "sed -i -e 's|regex-pcre-builtin >= .*|regex-pcre|' highlighting-kate.cabal";
  meta = {
    homepage = "http://github.com/jgm/highlighting-kate";
    description = "Syntax highlighting";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
