# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, deepseqGenerics, syb }:

cabal.mkDerivation (self: {
  pname = "pandoc-types";
  version = "1.16.1";
  sha256 = "846054157d7072ca3f7260b988a6752536b42bbd32c051400e55f46229b8179e";
  buildDepends = [ aeson deepseqGenerics syb ];
  meta = {
    homepage = "http://johnmacfarlane.net/pandoc";
    description = "Types for representing a structured document";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
